const state = {
  view: "home",
  communityTab: "global",
  selectedAvatar: "berry",
  ambience: "hallyu",
  selectedGroup: "skz",
  activityTab: "activity",
  profileTab: "posts",
  profileEditorOpen: false,
  homeFilter: "all",
  selectedHashtag: null,
  hashtagSort: "recent",
  expandedPosts: {},
  openPostMenu: null,
  reportTarget: null,
  hiddenPosts: {},
  mutedUsers: {},
  socialReports: [],
  toast: null,
  openComments: {},
  commentDrafts: {},
  replyTo: {},
  likedComments: {},
  savedPosts: {},
  sharedPosts: {},
  settingsPanel: null,
  viewedProfile: null,
  followedProfiles: {},
  selectedProfileBg: "army",
  activeStory: null,
  likedStories: {},
  storyDirection: 1,
  storyComposerOpen: false,
  storyEditorOpen: false,
  storyToolPanel: null,
  storyDraft: {
    type: "text",
    text: "Mi momento K-pop",
    sticker: "✨",
    elements: [{ id: "sticker-1", type: "sticker", content: "✨", x: 72, y: 18, size: 38, rotation: 0 }],
    selectedElementId: "sticker-1",
    mention: "",
    location: "",
    music: "Basic beat · safe loop",
    musicCategory: "Trending",
    background: "Neon pastel",
    mediaName: "",
    mediaUrl: "",
    mediaType: "",
  },
  ownStoryStatsOpen: false,
  ownStory: null,
  storyInbox: [],
  authMode: "login",
  isAuthenticated: false,
  user: null,
  session: null,
  supabase: null,
  backendMode: "local",
  livePosts: [],
  liveProfiles: [],
  newsItems: [],
  newsLoading: false,
  newsLastUpdated: null,
  newsFilter: {
    artist: "all",
    topic: "recent",
    status: "all",
    language: "all",
  },
};

let storyAutoTimer = null;

const titleByView = {
  home: "Tu universo K-pop latino",
  search: "Buscar",
  trends: "Trends K-pop",
  publish: "Crear publicacion",
  notifications: "Actividad e inbox",
  settings: "Ajustes",
  events: "Eventos fandom",
  market: "Marketplace oficial",
  news: "Noticias actuales",
  groups: "Grupos e idols",
  community: "Comunidades latinas",
  rookie: "Me quiero meter al K-pop",
  messages: "Mensajes privados",
  profile: "Perfil",
};

const storage = {
  get(key, fallback) {
    try {
      const value = localStorage.getItem(key);
      return value ? JSON.parse(value) : fallback;
    } catch {
      return fallback;
    }
  },
