-- HallyuHub Beta Real - K-pop entity profile editorial data.
-- Safe to run more than once. Does not delete real data or use unlicensed media.

create extension if not exists "pgcrypto";

create table if not exists public.kpop_entities (
  id uuid primary key default gen_random_uuid(),
  entity_type text not null default 'artist' check (entity_type in ('group', 'idol', 'artist')),
  name text not null,
  normalized_name text not null unique,
  aliases text[] not null default '{}',
  bio text not null default '',
  image_url text not null default '',
  image_source text not null default '',
  image_license text not null default '',
  attribution text not null default '',
  official_url text not null default '',
  is_verified boolean not null default false,
  status text not null default 'verified',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.kpop_entities
  add column if not exists fandom_name text not null default '',
  add column if not exists members jsonb not null default '[]'::jsonb,
  add column if not exists discography jsonb not null default '[]'::jsonb,
  add column if not exists debut_year text not null default '';

create unique index if not exists kpop_entities_normalized_name_uidx
  on public.kpop_entities (normalized_name);

insert into public.kpop_entities (
  entity_type,
  name,
  normalized_name,
  aliases,
  bio,
  fandom_name,
  members,
  discography,
  debut_year,
  is_verified,
  status
) values
  (
    'group',
    'BTS',
    'bts',
    array['Bangtan', 'Bangtan Sonyeondan', 'ARMY'],
    'Grupo surcoreano con una carrera global marcada por pop, hip-hop, performance y una conexion muy fuerte con ARMY.',
    'ARMY',
    '["RM","Jin","SUGA","j-hope","Jimin","V","Jungkook"]'::jsonb,
    '["2 Cool 4 Skool","Dark & Wild","Wings","Love Yourself","Map of the Soul: 7","BE","Proof"]'::jsonb,
    '2013',
    true,
    'verified'
  ),
  (
    'group',
    'BLACKPINK',
    'blackpink',
    array['BP', 'BLINK'],
    'Grupo con identidad visual fuerte, pop de alto impacto y presencia global en musica, moda y performance.',
    'BLINK',
    '["Jisoo","Jennie","Rose","Lisa"]'::jsonb,
    '["Square One","The Album","Born Pink"]'::jsonb,
    '2016',
    true,
    'verified'
  ),
  (
    'group',
    'Stray Kids',
    'stray kids',
    array['SKZ', 'STAY'],
    'Grupo reconocido por energia, produccion propia y una comunidad STAY muy activa.',
    'STAY',
    '["Bang Chan","Lee Know","Changbin","Hyunjin","Han","Felix","Seungmin","I.N"]'::jsonb,
    '["I am NOT","GO LIVE","NOEASY","5-STAR","ROCK-STAR"]'::jsonb,
    '2018',
    true,
    'verified'
  ),
  (
    'group',
    'NewJeans',
    'newjeans',
    array['NJZ', 'Bunnies'],
    'Grupo con estetica fresca, pop nostalgico y una forma moderna de conectar musica, moda y cultura digital.',
    'Bunnies',
    '["Minji","Hanni","Danielle","Haerin","Hyein"]'::jsonb,
    '["New Jeans","OMG","Get Up","How Sweet"]'::jsonb,
    '2022',
    true,
    'verified'
  ),
  (
    'group',
    'TWICE',
    'twice',
    array['ONCE'],
    'Grupo de larga trayectoria, conocido por canciones pop brillantes y una comunidad ONCE internacional.',
    'ONCE',
    '["Nayeon","Jeongyeon","Momo","Sana","Jihyo","Mina","Dahyun","Chaeyoung","Tzuyu"]'::jsonb,
    '["The Story Begins","Twicetagram","Eyes Wide Open","Formula of Love","Ready to Be"]'::jsonb,
    '2015',
    true,
    'verified'
  ),
  (
    'group',
    'SEVENTEEN',
    'seventeen',
    array['SVT', 'CARAT'],
    'Grupo con foco en performance, produccion y coreografias precisas, muy conectado con CARAT.',
    'CARAT',
    '["S.Coups","Jeonghan","Joshua","Jun","Hoshi","Wonwoo","Woozi","DK","Mingyu","The8","Seungkwan","Vernon","Dino"]'::jsonb,
    '["17 Carat","Teen, Age","An Ode","Face the Sun","FML"]'::jsonb,
    '2015',
    true,
    'verified'
  ),
  (
    'group',
    'ENHYPEN',
    'enhypen',
    array['ENGENE'],
    'Grupo con narrativa visual intensa, performance cuidada y fandom global en crecimiento.',
    'ENGENE',
    '["Jungwon","Heeseung","Jay","Jake","Sunghoon","Sunoo","Ni-ki"]'::jsonb,
    '["Border: Day One","Dimension: Dilemma","Manifesto: Day 1","Orange Blood"]'::jsonb,
    '2020',
    true,
    'verified'
  ),
  (
    'group',
    'TXT',
    'txt',
    array['TOMORROW X TOGETHER', 'MOA'],
    'Grupo con concepto juvenil, narrativa pop y estetica visual cambiante.',
    'MOA',
    '["Soobin","Yeonjun","Beomgyu","Taehyun","Huening Kai"]'::jsonb,
    '["The Dream Chapter: Star","The Chaos Chapter: Freeze","minisode 2","The Name Chapter: Temptation"]'::jsonb,
    '2019',
    true,
    'verified'
  ),
  (
    'group',
    'IVE',
    'ive',
    array['DIVE'],
    'Grupo con pop elegante, presencia escenica marcada y una estetica visual refinada.',
    'DIVE',
    '["Yujin","Gaeul","Rei","Wonyoung","Liz","Leeseo"]'::jsonb,
    '["Eleven","Love Dive","After Like","Ive IVE","Ive Switch"]'::jsonb,
    '2021',
    true,
    'verified'
  ),
  (
    'group',
    'LE SSERAFIM',
    'le sserafim',
    array['LESSERAFIM', 'FEARNOT'],
    'Grupo con concepto de confianza, performance potente y sonido pop moderno.',
    'FEARNOT',
    '["Sakura","Chaewon","Yunjin","Kazuha","Eunchae"]'::jsonb,
    '["Fearless","Antifragile","Unforgiven","Easy"]'::jsonb,
    '2022',
    true,
    'verified'
  ),
  (
    'group',
    'aespa',
    'aespa',
    array['MY'],
    'Grupo con identidad futurista, elementos digitales y sonido pop electronico.',
    'MY',
    '["Karina","Giselle","Winter","Ningning"]'::jsonb,
    '["Savage","Girls","Drama","Armageddon"]'::jsonb,
    '2020',
    true,
    'verified'
  ),
  (
    'group',
    'NCT',
    'nct',
    array['NCT 127', 'NCT DREAM', 'WayV', 'NCTzen'],
    'Proyecto con multiples unidades, estilos y una comunidad internacional amplia.',
    'NCTzen',
    '["NCT 127","NCT DREAM","WayV","NCT WISH"]'::jsonb,
    '["NCT 2018 Empathy","Resonance","Universe","Golden Age"]'::jsonb,
    '2016',
    true,
    'verified'
  ),
  (
    'group',
    'ATEEZ',
    'ateez',
    array['ATINY'],
    'Grupo conocido por performance intensa, narrativa aventurera y energia escenica.',
    'ATINY',
    '["Hongjoong","Seonghwa","Yunho","Yeosang","San","Mingi","Wooyoung","Jongho"]'::jsonb,
    '["Treasure EP.1","Zero: Fever Part.1","The World EP.1","Golden Hour"]'::jsonb,
    '2018',
    true,
    'verified'
  ),
  (
    'group',
    'EXO',
    'exo',
    array['EXO-L'],
    'Grupo con trayectoria destacada, voces fuertes y alto impacto en la historia moderna del K-pop.',
    'EXO-L',
    '["Xiumin","Suho","Lay","Baekhyun","Chen","Chanyeol","D.O.","Kai","Sehun"]'::jsonb,
    '["XOXO","Exodus","The War","Dont Mess Up My Tempo","Exist"]'::jsonb,
    '2012',
    true,
    'verified'
  ),
  (
    'idol',
    'Jungkook',
    'jungkook',
    array['Jeon Jungkook', 'JK', 'BTS'],
    'Artista e integrante de BTS destacado por su voz, performance y carrera solista global.',
    'ARMY',
    '[]'::jsonb,
    '["Seven","3D","Golden"]'::jsonb,
    '2013',
    true,
    'verified'
  ),
  (
    'idol',
    'Jimin',
    'jimin',
    array['Park Jimin', 'BTS'],
    'Artista e integrante de BTS reconocido por danza expresiva, tono vocal y presencia escenica.',
    'ARMY',
    '[]'::jsonb,
    '["Face","Like Crazy","Muse"]'::jsonb,
    '2013',
    true,
    'verified'
  ),
  (
    'idol',
    'Lisa',
    'lisa',
    array['Lalisa', 'BLACKPINK'],
    'Artista e integrante de BLACKPINK reconocida por baile, carisma escenico y alcance global.',
    'BLINK',
    '[]'::jsonb,
    '["Lalisa","Money","Rockstar"]'::jsonb,
    '2016',
    true,
    'verified'
  ),
  (
    'idol',
    'Jennie',
    'jennie',
    array['Jennie Kim', 'BLACKPINK'],
    'Artista e integrante de BLACKPINK con identidad musical, visual y de performance propia.',
    'BLINK',
    '[]'::jsonb,
    '["Solo","You & Me"]'::jsonb,
    '2016',
    true,
    'verified'
  ),
  (
    'idol',
    'Bang Chan',
    'bang chan',
    array['Christopher Bang', 'Stray Kids', 'SKZ'],
    'Artista e integrante de Stray Kids asociado a liderazgo, produccion y conexion cercana con fans.',
    'STAY',
    '[]'::jsonb,
    '["SKZ-Player","Mixtape","3RACHA"]'::jsonb,
    '2018',
    true,
    'verified'
  )
on conflict (normalized_name) do update set
  entity_type = excluded.entity_type,
  name = excluded.name,
  aliases = excluded.aliases,
  bio = excluded.bio,
  fandom_name = excluded.fandom_name,
  members = excluded.members,
  discography = excluded.discography,
  debut_year = excluded.debut_year,
  is_verified = excluded.is_verified,
  status = excluded.status,
  updated_at = now();
